name = "BridgeSDEInference"
uuid = "46d747a0-b9e1-11e9-14b5-615c73e45078"
authors = ["Marcin Mider <marcin.mider@gmail.com>", "mschauer <moritzschauer@web.de>"]
version = "0.1.0"

[deps]
Bridge = "2d3116d5-4b8f-5680-861c-71f149790274"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GaussianDistributions = "43dcc890-d446-5863-8d1a-14597580bb8d"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
