name = "BridgeSDEInference"
uuid = "46d747a0-b9e1-11e9-14b5-615c73e45078"
authors = ["Marcin Mider <marcin.mider@gmail.com>", "mschauer <moritzschauer@web.de>"]
version = "0.2.0"

[deps]
Bridge = "2d3116d5-4b8f-5680-861c-71f149790274"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GaussianDistributions = "43dcc890-d446-5863-8d1a-14597580bb8d"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"

[extras]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Statistics", "Random", "LinearAlgebra"]


[compat]
julia = "1"
Bridge = "0.9, 0.10"
DataFrames = "0.19"
Distributions = "0.21"
ForwardDiff = "0.10"
GaussianDistributions = "0.3.2"
Interpolations = "0.12"
Parameters = "0"
StaticArrays = "0"
Suppressor = "0.1.1"
